name: C++ CI

on:
  push:
    branches: [yacc-with-AST-C]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        run: sudo apt install flex bison g++
      - name: Execute Program
        run: make
